apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  strategy: 
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      restartPolicy: Always
      containers:
        - name: app-container
          imagePullPolicy: Always
          image: "{{ .Values.appImage }}"
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "develop"
            - name: DB_USER
              value: "tomer"
            - name: DB_PASSWORD
              value: "1234"
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service-with-db
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
